# Generated by Django 5.2.12 on 2026-03-23 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_utilisateur_date_de_naissance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='code_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
