"""
Django settings for Projet project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

 


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-$c1bgu$8o2bqx6d6z=f%*8f)^lvhr2=ff&s8-$ct!24oblf_&c')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'users',
    'produits',
    'widget_tweaks',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Projet.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Projet.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

#=============ajouter pour pouvoir controler l'authentification==================
AUTH_USER_MODEL = 'users.Utilisateur'


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')




# 🔹 MEDIA_URL définit l'URL publique qui permettra d'accéder aux fichiers média (images, vidéos, etc.).
# Par exemple, une image stockée dans 'media/produits/chaussure.jpg' sera accessible via :
# http://localhost:8000/media/produits/chaussure.jpg
MEDIA_URL = '/media/'

# 🔹 MEDIA_ROOT définit le chemin physique où seront enregistrés les fichiers média sur le serveur.
# Django stockera tous les fichiers uploadés dans ce dossier.
# Ici, on utilise os.path.join(BASE_DIR, 'media') pour placer ce dossier à la racine du projet.
# Cela signifie que toutes les images téléchargées seront stockées dans : 
# /mon_projet/media/
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Celery Configuration
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    'notification-stock-8h': {
        'task': 'produits.tasks.notification_quotidienne_stock',
        'schedule': crontab(hour=8, minute=0),
    },
}

# Email Configuration (Console for development)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

EMAIL_HOST = 'smtp-relay.brevo.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = '9f4b2a001@smtp-brevo.com'
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', 'K7VXJCdE8cx3rDmY')
DEFAULT_FROM_EMAIL = 'sasukenozel@gmail.com'
ADMIN_EMAILS = ['siddick369@gmail.com', 'securite@infracontrol.com']

FRONTEND_URL = 'http://localhost:8000'

# Groq API (IA Moderation)
GROQ_API_KEY = os.environ.get('GROQ_API_KEY', '')

# Config HUB
HUB_EMAIL = 'sasukenozel@gmail.com'  # TODO: Remplacer par l'email réel
HUB_WHATSAPP_NUMBER = '237678317658'  # Numéro WhatsApp (format international Cameroun)

# =============================================
# Configuration WhatsApp Bot
# =============================================
# Fournisseur: 'green_api' (recommandé) ou 'callmebot'
WHATSAPP_PROVIDER = os.environ.get('WHATSAPP_PROVIDER', 'green_api')

# --- Green API (green-api.com) ---
# 1. Créer un compte sur https://green-api.com
# 2. Créer une instance et scanner le QR code avec WhatsApp
# 3. Copier l'idInstance et l'apiTokenInstance
GREEN_API_ID_INSTANCE = os.environ.get('GREEN_API_ID_INSTANCE', '')
GREEN_API_TOKEN = os.environ.get('GREEN_API_TOKEN', '')

# --- CallMeBot (callmebot.com) - Alternative ---
# 1. Envoyer "I allow callmebot to send me messages" au +34 644 59 71 67
# 2. Récupérer la clé API reçue par message
CALLMEBOT_API_KEY = os.environ.get('CALLMEBOT_API_KEY', '')
