# Generated by Django 5.2.12 on 2026-03-23 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0003_alter_historiqueproduit_action_commande'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='nom_du_site',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom du site'),
        ),
        migrations.AddField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('acseptee', 'Acceptée'), ('refusee', 'Refusée')], default='en_attente', max_length=20),
        ),
    ]
