# Generated by Django 5.2.12 on 2026-03-23 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0004_commande_nom_du_site_commande_statut'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='demandeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retours', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='produit',
            name='lieu_implantation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='nom_livreur',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='societe_livraison',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='type_ajout',
            field=models.CharField(choices=[('livraison', 'Livraison'), ('retour_magasin', 'Retour de magasin')], default='livraison', max_length=20),
        ),
        migrations.AddField(
            model_name='produit',
            name='unite',
            field=models.CharField(blank=True, default='Unité', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historiqueproduit',
            name='action',
            field=models.CharField(choices=[('ajout', 'Ajout'), ('livraison', 'Livraison'), ('retour_magasin', 'Retour de magasin'), ('modification', 'Modification'), ('suppression', 'Suppression'), ('exporter en CSV', 'Exporter en CSV'), ('exporter en PDF', 'Exporter en PDF')], max_length=20),
        ),
    ]
